### VARIABILI GLOBALI
@baseUrl = http://localhost:3000
# Da sostituire con il token ottenuto dopo il login 
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoicGxheWVyMSIsImlhdCI6MTc3OTg3ODQ0NiwiZXhwIjoxNzc5OTY0ODQ2fQ.keW7fYM5CltWH83nrf6bx23h9N_pnbNHs5E6Wp_uops

### ==========================================
### AUTH ROUTER
### ==========================================

### Crea nuovo utente
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "usr": "player1",
  "pwd": "passwordSegreta123"
}

###

### Login (mi da il token)
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "usr": "player1",
  "pwd": "passwordSegreta123"
}


### ==========================================
### PUBLIC ROUTER
### ==========================================

### Classifica generale
GET {{baseUrl}}/leaderboard

###

### Lista delle partite concluse
GET {{baseUrl}}/archive

### Dettaglio di una singola partita conclusa
# @prompt idPartita Inserisci l'ID della partita
GET {{baseUrl}}/archive/{{idPartita}}


### ==========================================
### GAME ROUTER
### ==========================================

### Partite personali
GET {{baseUrl}}/games
Authorization: Bearer {{authToken}}

###

### Inizia nuova partita
POST {{baseUrl}}/games/start
Authorization: Bearer {{authToken}}

###

### Recupera info partita
# @prompt idPartita Inserisci l'ID della partita
GET {{baseUrl}}/games/{{idPartita}}
Authorization: Bearer {{authToken}}

### Tentativo parola
# @prompt idPartita Inserisci l'ID della partita
POST {{baseUrl}}/games/{{idPartita}}/guess
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "word": "Hood"
}

###

### Resa
# @prompt idPartita Inserisci l'ID della partita
POST {{baseUrl}}/games/{{idPartita}}/surrender
Authorization: Bearer {{authToken}}